### ISSUE TITLE
Container lags on iPhone

### ISSUE THREAD

**Issue by l174rd** [eduardomb/scroll-up-bar#16]
Hi,
I implemented Scroll-up-bar in a project. When I scroll down on the iPhone screen, the topbar hides, but if I scroll down again, the topbar-container doesn't hide automatically. It hides for a **short time** and **appears again**. Can anyone reproduce this or does anyone know what kind of bug this is?

I initiate the scrollbar like this:

``` javascript
$('#topbar').scrollupbar();
```

My HTML markup:

``` html
<div id="topbar" class="navbar">
    <div class="topbar-inner">
        <ul id="mobile-navigation" class="nav menu">
            <li>foo</li>
            <li>bar</li>
        </ul>
    </div>
</div>
```

My LESS file:

``` css
#topbar {
    box-sizing: border-box;
    width: 100%;
    top: 0;
    left: 0;
    z-index: 1337;
    margin-bottom: 0;
    position: absolute;

    .topbar-inner {
        background: @bodyFontColor;
        height: 100%;
    }
}
```

The other problem is when I click on the button to collapse in the menu, it expands the bootstrap navbar but it **wiggles**. Can you help me out?
